config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  controllers: { omniauth_callbacks: "users/omniauth_callbacks", session: 'users/sessions', registration: 'users/registrations' }

  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new', as:  :sign_up
    get 'sign_in', to: 'devise/sessions#new', as:  :sign_in
    get 'logout', to: 'devise/sessions#destroy', as:  :logout , method: :delete
  end
  resources :tree_views
  root to: 'home#index'
  resources :main
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/tree_views_controller.rb
require 'open-uri'
class TreeViewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tree_view, only: [:show, :edit, :update, :destroy]

  # GET /tree_views
  # GET /tree_views.json
  def index
    @tree_views = current_user.tree_views.all
  end

  # GET /tree_views/1
  # GET /tree_views/1.json
  def show
    path = File.join Rails.root, 'public', 'system', 'json_files', '000', '000', "00#{@tree_view.id}", 'original'
    FileUtils.mkdir_p(path) unless File.exist?(path)
    File.open("#{path}/tree.json","w+") unless File.exist?("#{path}/tree.json")
    if @tree_view.file.present?
        @tree = TreeMap.new(path,root_url+@tree_view.file.url,@tree_view.id)
    else
      @tree = TreeMap.new(path,@tree_view.link,@tree_view.id)
    end
  end

  # GET /tree_views/new
  def new
    @tree_view = current_user.tree_views.new
  end

  # GET /tree_views/1/edit
  def edit
  end

  # POST /tree_views
  # POST /tree_views.json
  def create
    @tree_view = current_user.tree_views.new(tree_view_params)
    respond_to do |format|
      if @tree_view.save
        format.html { redirect_to @tree_view, notice: 'Tree view was successfully created.' }
        format.json { render :show, status: :created, location: @tree_view }
      else
        format.html { render :new }
        format.json { render json: @tree_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tree_views/1
  # PATCH/PUT /tree_views/1.json
  def update
    respond_to do |format|
      if @tree_view.update(tree_view_params)
        format.html { redirect_to @tree_view, notice: 'Tree view was successfully updated.' }
        format.json { render :show, status: :ok, location: @tree_view }
      else
        format.html { render :edit }
        format.json { render json: @tree_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tree_views/1
  # DELETE /tree_views/1.json
  def destroy
    @tree_view.destroy
    respond_to do |format|
      format.html { redirect_to tree_views_url, notice: 'Tree view was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree_view
      @tree_view = TreeView.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tree_view_params
      params.require(:tree_view).permit(:link, :file, :user_id)
    end
end

app/helpers/tree_views_helper.rb
module TreeViewsHelper
end

app/views/tree_views/_form.html.erb
<%= form_for(tree_view, html: { multipart: true } )do |f| %>
  <% if tree_view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tree_view.errors.count, "error") %> prohibited this tree_view from being saved:</h2>

      <ul>
      <% tree_view.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <%= f.file_field :file %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tree_views/edit.html.erb
<h1>Editing Tree View</h1>

<%= render 'form', tree_view: @tree_view %>

<%= link_to 'Show', @tree_view %> |
<%= link_to 'Back', tree_views_path %>

app/views/tree_views/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tree Views</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tree_views.each do |tree_view| %>
      <tr>
        <td><%= tree_view.link %></td>
        <td><%= link_to 'Show', tree_view %></td>
        <td><%= link_to 'Edit', edit_tree_view_path(tree_view) %></td>
        <td><%= link_to 'Destroy', tree_view, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tree View', new_tree_view_path %>

app/views/tree_views/new.html.erb
<h1>New Tree View</h1>

<%= render 'form', tree_view: @tree_view %>

<%= link_to 'Back', tree_views_path %>

app/views/tree_views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @tree_view.link %>
  <div id="tree" class="tree">
  </div>
</p>

<%= link_to 'Edit', edit_tree_view_path(@tree_view) %> |
<%= link_to 'Back', tree_views_path %>